### ISSUE TITLE
a href "colcarou-button" - Hyperlink doesn't work

### ISSUE THREAD

**Issue by JaySMa** [Sourge/colcarou#1]
Hello..
Thank you for creating this, works well.  

Except, for the hyperlink button; clicking it doesn't.

Even with example at: http://colcarou.niclas-geiger.de/, the button hyperlink won't link back to the # in the URL.

Thank you ..

**Comment by JaySMa** [comment]
In testing, any hyperlink within the colcaroi-textbox div doesn't work.

Thank you..

**Comment by niclasgeiger** [comment]
Ah yeah, you're right. There is an updated (but rather project specific) version on my pc right now. I try to upload it in a more general style in the next days. 
That version has working buttons and should also provide responsive views + auto sliding.

**Comment by JaySMa** [comment]
Great, thank you for the update.

**Comment by niclasgeiger** [comment]
So i got the bug fixed ( I guess). Just need to get some more testing done and format the code. I'm aiming for releasing the update coming friday

**Comment by niclasgeiger** [comment]
New release just went live. This bug should be fixed now. Thanks for your issue reporting man. Appreciate it!
